"""Add soft delete

Revision ID: 2f1e6ef206d1
Revises: 78f0c74bdd33
Create Date: 2026-05-09 03:33:31.915891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1e6ef206d1'
down_revision: Union[str, None] = '78f0c74bdd33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'deleted_at')
    # ### end Alembic commands ###
